"""
Fit the etalon spectrum model and tabulate the fit results.

``iterative_fit`` fits the peak model to a 1D extracted etalon spectrum.
``insert_peak_parameters`` and ``insert_polynomial_parameters`` collect
the per-peak and per-order polynomial parameters from the fit results
into pandas dataframes, which the caller stores as the ``PEAKS`` and
``POLY`` FITS tables.
"""
import os
import pickle
import time
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

from .maroon_x_fit_object import MaroonXFit, FitResult

from . import get_logger

PLOT_FORMAT = "png"


def insert_peak_parameters(results):
    """
    Extract the parameters for each fitted peak into a table.

    Parameters
    ----------
    results : list of FitResult
        Results of the fits generated by the iterative fit. Each element
        must additionally carry ``fiber``, ``order`` and ``recording_time``
        attributes, attached by the caller (``getPeaksAndPolynomials``);
        these are not fields of the FitResult class itself.

    Returns
    -------
    DataFrame
        Pandas dataframe with one row per fitted peak, suitable for
        conversion to a FITS table. Columns:

        - ``FIBER`` : fiber tag of the fit result
        - ``ORDER`` : order tag of the fit result
        - ``OFFSET`` : fitted spectrum offset
        - ``CENTER`` : fitted peak center position (pixel)
        - ``AMPLITUDE`` : fitted peak amplitude
        - ``SIGMA1`` : left sigma polynomial evaluated at the peak center
        - ``SIGMA2`` : right sigma polynomial evaluated at the peak center
        - ``WIDTH`` : width polynomial evaluated at the peak center
        - ``RECORDED`` : recording time tag
        - ``LQ_COST`` : least-squares cost of the individual peak fit
        - ``LQ_STATUS`` : least-squares status of the individual peak fit
    """
    peaks = pd.DataFrame()

     # Making the empty columns
    fiber_list = []
    order_list = []
    offset_list = []
    center_list = []
    amplitude_list = []
    sigma1_list = []
    sigma2_list = []
    width_list = []
    recorded_list = []
    lq_cost_list = []
    lq_status_list = []

    for result in results:

        # Unpack necessary parameters

        result_obj = result.fit_obj
        parameters = result_obj.param_obj

        offset = parameters.offset
        fits = parameters.eval_polynomials_at_centers()

        for values, f in zip(fits.T, result.peak_fit_results):
            center, amplitude, sigma1, sigma2, width = values

            # Append the values to the columns
            fiber_list.append(result.fiber)
            order_list.append(result.order)
            offset_list.append(offset)
            center_list.append(center)
            amplitude_list.append(amplitude)
            sigma1_list.append(sigma1)
            sigma2_list.append(sigma2)
            width_list.append(width)
            recorded_list.append(result.recording_time)
            lq_cost_list.append(f.cost)
            lq_status_list.append(f.status)

    # Insert the columns into the dataframe
    peaks['FIBER'] = fiber_list
    peaks['ORDER'] = order_list
    peaks['OFFSET'] = offset_list
    peaks['CENTER'] = center_list
    peaks['AMPLITUDE'] = amplitude_list
    peaks['SIGMA1'] = sigma1_list
    peaks['SIGMA2'] = sigma2_list
    peaks['WIDTH'] = width_list
    peaks['RECORDED'] = recorded_list
    peaks['LQ_COST'] = lq_cost_list
    peaks['LQ_STATUS'] = lq_status_list

    return peaks

def insert_polynomial_parameters(results):
    """
    Extract polynomial parameters from fit results into a table.

    Parameters
    ----------
    results : list of FitResult
        Results of the fits generated by the iterative fit. Each element
        must additionally carry ``fiber``, ``order`` and ``recording_time``
        attributes, attached by the caller (``getPeaksAndPolynomials``);
        these are not fields of the FitResult class itself.

    Returns
    -------
    DataFrame
        Pandas dataframe with one row per fitted fiber/order. Columns:

        - ``recorded`` : recording time tag
        - ``fiber`` : fiber tag of the fit result
        - ``order`` : order tag of the fit result
        - ``fitrange`` : fitted pixel range, stored as
          ``[first pixel, last pixel + 1]``
        - ``offset`` : fitted spectrum offset
        - ``lq_cost`` : least-squares cost of the polynomial fit
        - ``lq_status`` : least-squares status of the polynomial fit
        - ``sigma_l_coefficients``, ``sigma_r_coefficients`` : left and
          right sigma polynomial coefficients, present only when
          ``meta_parameters.use_sigma_lr`` is True
        - ``sigma_coefficients`` : sigma polynomial coefficients, present
          only when ``meta_parameters.use_sigma_lr`` is False
        - ``width_coefficients`` : width polynomial coefficients

    Raises
    ------
    ValueError
        When the fit results do not all share the same meta parameters
        (``sigma``, ``width`` and ``use_sigma_lr`` are checked).
    """
    result_obj_0 = results[0].fit_obj
    meta_parameters = result_obj_0.param_obj.meta_parameters

    #Check valid meta_parameters.  Do not check total and number of peaks.
    for result in results:
        result_obj = result.fit_obj
        if not result_obj.param_obj.meta_parameters.sigma == meta_parameters.sigma\
            and result_obj.param_obj.meta_parameters.width == meta_parameters.width\
            and result_obj.param_obj.meta_parameters.use_sigma_lr == meta_parameters.use_sigma_lr:
            raise ValueError('All meta_parameters must be the same')

    poly = pd.DataFrame()
    # Make the empty columns
    recorded_list = []
    fiber_list = []
    order_list = []
    fitrange_list = []
    offset_list = []
    lq_cost_list = []
    lq_status_list = []
    if meta_parameters.use_sigma_lr:
        sigma_l_coefficients_list = []
        sigma_r_coefficients_list = []
    else:
        sigma_coefficients_list = []
    width_coefficients_list = []

    # Get the polynomial parameters and insert into dataframe
    for result in results:
        result_obj = result.fit_obj
        values = result_obj.param_obj.split_parameters()
        offset, p_sigma_l, p_sigma_r, p_width, _, _ = values

        f = result.polynomial_fit_result

        # Append the values to the columns
        recorded_list.append(result.recording_time)
        fiber_list.append(result.fiber)
        order_list.append(result.order)

        fit_obj = result.fit_obj
        fitrange_list.append(
            [int(fit_obj.fitrange[0]), int(fit_obj.fitrange[-1]) + 1]
        )

        offset_list.append(offset)
        lq_cost_list.append(f.cost)
        lq_status_list.append(f.status)
        if meta_parameters.use_sigma_lr:
            sigma_l_coefficients_list.append(np.asarray(p_sigma_l, dtype=float))
            sigma_r_coefficients_list.append(np.asarray(p_sigma_r, dtype=float))
        else:
            sigma_coefficients_list.append(np.asarray(p_sigma_l, dtype=float))

        width_coefficients_list.append(np.asarray(p_width, dtype=float))

    # Insert the columns into the dataframe
    poly['recorded'] = recorded_list
    poly['fiber'] = fiber_list
    poly['order'] = order_list
    poly['fitrange'] = fitrange_list
    poly['offset'] = offset_list
    poly['lq_cost'] = lq_cost_list
    poly['lq_status'] = lq_status_list
    if meta_parameters.use_sigma_lr:
        poly['sigma_l_coefficients'] = sigma_l_coefficients_list
        poly['sigma_r_coefficients'] = sigma_r_coefficients_list
    else:
        poly['sigma_coefficients'] = sigma_coefficients_list
    poly['width_coefficients'] = width_coefficients_list

    return poly

def _calculate_residuals(observed, predicted, clip_range=None, clip_sigma=3, bad_flag=True):
    """
    Calculate summed relative residuals between observed and predicted values.

    Residuals are computed as ``np.abs((predicted - observed) / predicted)``,
    i.e. the absolute value of the residual relative to the predicted value.
    Residuals beyond ``clip_sigma`` times the standard deviation (ignoring
    NaNs) are set to NaN and excluded from the sums. The sum is returned
    both as-is and normalized by the number of samples.

    Parameters
    ----------
    observed : ndarray
        Observed data values. Must have the same shape as ``predicted``.

    predicted : ndarray
        Predicted model values. Must have the same shape as ``observed``.

    clip_range : tuple of two floats or None
        If not None, residuals are clipped (``np.clip``) to the
        ``(min, max)`` range before sigma clipping. Default is None.

    clip_sigma : float
        Sigma-clipping threshold. Residuals larger than ``clip_sigma`` times
        the NaN-ignoring standard deviation of the residuals are set to NaN,
        and the number of masked outliers is logged. Default is 3.

    bad_flag : bool
        If True, count residuals greater than 2 and log that count as
        outliers. This is logging-only: the code that would set those
        datapoints to NaN in ``observed`` is commented out, so ``bad_flag``
        does not modify the data or the returned values. Default is True.

    Returns
    -------
    resis : float
        Sum (``np.nansum``) of the residuals after clipping and sigma
        masking.

    norm_residuals : float
        ``resis`` divided by the number of non-NaN residual samples.
    """
    log = get_logger()

    residuals = np.abs((predicted - observed) / predicted)

    if bad_flag:
        # record outliers for logging
        bad = np.where(residuals > 2)
    
    if clip_range is not None:
        clip_min, clip_max = clip_range
        residuals = np.clip(residuals, clip_min, clip_max)    
    
    mask = np.where(residuals >  clip_sigma * np.nanstd(residuals))
    residuals[mask] = np.nan
    if mask[0].size > 0:
        log.fullinfo(f"Calculated residuals masked {mask[0].size} outliers "
        f"with sigma clipping at {clip_sigma} sigma")

    if bad_flag:
        #observed[bad] = np.nan
        num_bad = np.count_nonzero(bad)
        log.info(f"Clip {num_bad} datapoints as outliers when calculating residuals")

    resis = np.nansum(residuals)
    samples = np.sum(~np.isnan(residuals))
    norm_residuals = resis / samples

    return resis, norm_residuals

def iterative_fit(
        input_spectrum,
        degree_sigma,
        degree_width,
        iterations=3,
        guess_spectrum=None,
        fiber="",
        plot_path="",
        use_sigma_lr=True,
        show_plots=False,
        log=None
    ):
    """
    Fit a model to an etalon spectrum.

    QUICK-FIX (2021-09-08, AS): Replace (not supported) guess parameters
    from guess file with guess spectrum from this file to run guess on the
    data. Useful not as a 'speed-up' but for potentially bad/contaminated
    data that need a good first guess

    TODO: possible refinements:
        - Evaluate the cost function or the change in peak center positions
          as stop criterion.
        - An initial_guess could be used. Typically, we will have a set of data
          that is very similar to each other (e.g. etalon spectra of one day).
          The initial_guess can be used to speed up fitting as long as the
          changes in between spectra are small.

    TODO: at the moment there is only one global function for sigma and sigma1
    and sigma2 is forced to be identical. However, it is more precise to
    describe left and right wings of the peaks with seperate sigmas. -> make
    two global functions to make seperate functional describtion of sigma for
    left and right

    Parameters
    ----------
    input_spectrum : ndarray
        Recorded etalon spectrum.

    degree_sigma : int
        Degree of the polynomial for the peak sigmas.

    degree_width : int
        Degree of the polynomial for the peak widths.

    iterations : int
        Number of iterations to fit. Default is 3.

    guess_spectrum : ndarray
        Extracted etalon spectrum from a previous fit (see TODO). If given,
        it is used for the initial fit instead of ``input_spectrum``.
        Default is None.

    fiber : str
        Fiber to process. Only used to generate filenames for debug plots
        and for log messages. Default is an empty string.

    plot_path : str
        Location at which to generate and save debug plots. Default is an
        empty string.

    use_sigma_lr : bool
        Use different polynomials for the left and right sides of the peak
        wings, instead of a single sigma. Default is True.

    show_plots : bool
        Show the plots after each iteration. Default is False.

    log : Logger
        Logger to use for logging messages. If None, a default logger is
        created.

    Returns
    -------
    FitResult
        Result of the fit to the MaroonX spectrum, with fields:

        - ``fit_obj`` : MaroonXFit object that was fitted
        - ``fit_duration`` : time it took to fit the spectrum
        - ``iterations`` : number of iterations to fit (the requested
          maximum, passed through unchanged)
        - ``polynomial_fit_result`` : result of the polynomial fit
        - ``peak_fit_results`` : result of the peak fit

    Raises
    ------
    FitError
        When the polynomial fit does not succeed, or when the fitted
        amplitudes, sigma, or width evaluate to a value below zero.

    PeakError
        When peak finding (run inside the MaroonXFit constructor) detects
        an inconsistent number of peaks, i.e. unequal counts of minima
        and maxima.

    Notes
    -----
    Each iteration alternates a polynomial fit (``fit_polynomials``) and a
    peak-center fit (``fit_peak_centers``). The loop stops early when the
    normalized residuals change by less than 5% relative to the previous
    iteration. On that converging iteration, if the residuals improved,
    the new parameters are kept; otherwise the parameters revert to the
    state after the polynomial fit but before the last peak-center fit,
    matching the legacy etalon_fit.py behavior. If the loop exhausts all
    iterations without converging, a warning is logged.
    """
    t0 = time.time()

    if log is None:
        # If no logger is provided, create a default logger
        log = get_logger()
    
    # If there is a guess spectrum, use this for the first iteration of fitting data
    if guess_spectrum is not None:
        fit_spectrum = guess_spectrum
        log.fullinfo("Use guess spectrum for initial fit")
    else:
        # Otherwise use the input spectrum for the first iteration
        fit_spectrum = input_spectrum

    # Create fit parameters for initial fit
    fit_object = MaroonXFit(
        data=fit_spectrum,
        degree_sigma=degree_sigma,
        degree_width=degree_width,
        fiber=fiber,
        plot_path=plot_path,
        use_sigma_lr=use_sigma_lr
    )

    if plot_path:
        f2 = os.path.join(plot_path, f"initial_guess_{fiber}.{PLOT_FORMAT}")
        fit_object.plot_fit(filename=f2)

    # If provided with the guess spectrum,
    # fit the peak centers using the parameters from the guess file
    if guess_spectrum is not None:
        data = input_spectrum[fit_object.fitrange]
        fit_object.update_maroonxfit(data=data)
        fit_results = fit_object.fit_peak_centers(iteration=0, fiber=fiber)

    shw = fit_object.eval_polynomials()[2, :] #shw is slit half width
    log.fullinfo(f"Slit half-width on {fiber} (0. iteration): {shw[0]:.3f} - {shw[-1]:.3f}")

    amplitudes_sorted = np.sort(fit_object.eval_polynomials_at_centers()[1, :])
    log.fullinfo(f"Flat-relative amplitudes on {fiber} (0. iteration):\
            min: {amplitudes_sorted[10]}, {amplitudes_sorted[-10]}, median: {np.median(amplitudes_sorted)}")

    #Get the required data to calculate residuals
    spectrum_values = fit_object.spectrum_val()
    data = fit_object.data

    # Calculate residuals
    residuals, norm_residuals = _calculate_residuals(
        data, spectrum_values, clip_range=(0, 2), clip_sigma=5, bad_flag=True)

    log.fullinfo(f"Fit residuals on {fiber} (0. iteration): {residuals:.1f} ({norm_residuals:.3f})")
    # log.fullinfo(f"Degree sigma: {degree_sigma}, degree width: {degree_width}")
    log.fullinfo(f"Created fit parameters for {fiber} in {time.time() - t0:.2f} s")

    if show_plots:
        fit_object.plot_fit()
        plt.show()

    t0 = time.time()

    old_resis_norm = 10 # Set to a high value to ensure that the first iteration is always run
    converged = False

    parameter_list = []
    for i in range(1, iterations):
        t_i = time.time()

        # Save the parameters from the previous iterations in a list.
        parameter_list.append(np.copy(fit_object.param_obj.parameters))

        resf = fit_object.fit_polynomials()
        params_after_poly = np.copy(fit_object.param_obj.parameters)
        shw = fit_object.eval_polynomials()[2, :]
        amplitudes_sorted = np.sort(fit_object.eval_polynomials_at_centers()[1,:])

        log.fullinfo(f"Fitted polynomials ({i}. iteration) on {fiber} in: {time.time() - t_i:.2f} s")
        log.fullinfo(f"Slit half-width on {fiber} ({i}. iteration): {shw[0]:.3f} - {shw[-1]:.3f}")
        log.fullinfo(f"Flat-relative amplitudes on {fiber} ({i}. iteration):\
                 min: {amplitudes_sorted[10]:.2f}, max: {amplitudes_sorted[-10]:.2f},\
                      median: {np.median(amplitudes_sorted):.2f}")

        t_i = time.time()
        fit_results = fit_object.fit_peak_centers(iteration=i, fiber=fiber)

        log.fullinfo(f"Fitted centers ({i}. iteration) on {fiber} in: {time.time() - t_i:.2f} s")

        spectrum_values = fit_object.spectrum_val()

        residuals, resis_norm = _calculate_residuals(
            data, spectrum_values, clip_range=(0, 1), clip_sigma=3, bad_flag=False)

        log.fullinfo(f"Fit residuals on {fiber} ({i}. iteration):\
                 {residuals:.1f} ({resis_norm:.3f})")


        # If new residuals differ less than 5% from old residuals, stop iterating
        if np.abs(resis_norm - old_resis_norm) < 0.05 * old_resis_norm:
            converged = True
            if resis_norm < old_resis_norm:
                # if we see an improvement, keep the new parameters and increment the iterator
                i = i + 1
                parameter_list.append(np.copy(fit_object.param_obj.parameters))
            else:
                # No improvement: revert to the post-polynomial-fit state (before the
                # last fit_peak_centers), matching legacy etalon_fit.py where p[-1] is
                # appended after fit_polynomials but before fit_peak_centers on the
                # converging iteration.
                fit_object.param_obj.update_parameters(parameters=params_after_poly)
            break
        else:
            parameter_list.append(np.copy(fit_object.param_obj.parameters))
        old_resis_norm = resis_norm

    if converged:
        log.fullinfo(f"No more improvement for {fiber} after {i-1} iteration, finished")
    else:
        log.warning(f"Global fit did not converge for {fiber} after {i+1} iteration")

    if show_plots:
        fit_object.plot_fit()
        plt.show()

    if plot_path: # Save the final fit to the path provided
        f1 = os.path.join(plot_path, f"fit_{fiber}.{PLOT_FORMAT}")
        fit_object.plot_fit(filename=f1)
        f2 = os.path.join(plot_path, f"iterations_{fiber}.npz")
        np.savez_compressed(f2, *parameter_list, x=fit_object.fitrange,\
        spectrum=spectrum_values, data=data, bounds=fit_object.parameters_bounds)
        f3 = os.path.join(plot_path, f"meta_parameters_{fiber}.pkl")
        with open(f3, "wb") as f:
            pickle.dump(fit_object.param_obj.meta_parameters, f)

    t_total = time.time() - t0
    log.fullinfo(f"Fitting {fiber} done in {t_total:.2f} s")
    return FitResult(fit_object, t_total, iterations, resf, fit_results)
