#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MaroonX DRAGONS Documentation - Master Configuration
=====================================================

This is the unified Sphinx configuration for all MaroonX documentation,
including User Manual, Programmer Manual, and Tutorial.
"""

import os
import pathlib
import sys

# -- Path setup ----------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

# this path is pointing to MAROONXDR/doc/
CURRENT_PATH = pathlib.Path(os.path.abspath(os.path.dirname(__file__)))
MX_PATH = CURRENT_PATH.parent

sys.path.insert(0, str(MX_PATH))

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.imgmath',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx_rtd_theme',
    'sphinx_copybutton',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'MaroonX DRAGONS'
copyright = '2025, MaroonX Team'
author = 'MaroonX Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1.0'

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    # Exclude individual manual build directories
    'usermanuals/MAROONXDR_UserManual/_build',
    'progmanuals/MAROONXDR_ProgManual/_build',
    'tutorials/MAROONXDR_Tutorial/_build',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
todo_link_only = True

# -- Autosummary configuration --------------------------------------------

# Generate autosummary stub pages
autosummary_generate = True
autosummary_imported_members = False

# -- Copybutton configuration ---------------------------------------------

# Configure copybutton to exclude prompts and comment lines
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
# Exclude lines starting with # (comments)
copybutton_exclude = '.highlight-bash .c1, .highlight-python .c1, .highlight .c1'


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.
html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom CSS files
html_css_files = [
    'custom.css',
]

# Custom sidebar templates
# html_sidebars = {}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'MaroonXDRAGONSdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # This will remove blank pages.
    'classoptions': ',openany,oneside',
    'babel': '\\usepackage[english]{babel}',
}

# Grouping the document tree into LaTeX files.
latex_documents = [
    (master_doc, 'MaroonXDRAGONS.tex', 'MaroonX DRAGONS Documentation',
     'MaroonX Team', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'usermanuals/MAROONXDR_UserManual/images/GeminiLogo_new_2014.jpg'


# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'maroonxdragons', 'MaroonX DRAGONS Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (master_doc, 'MaroonXDRAGONS', 'MaroonX DRAGONS Documentation',
     author, 'MaroonXDRAGONS',
     'Data reduction pipeline for MaroonX spectrograph using DRAGONS framework',
     'Miscellaneous'),
]

# -- Autoapi configuration removed ------------------------------------------------
# AutoAPI has been removed - using sphinx.ext.autodoc instead

# -- Autodoc configuration ------------------------------------------------

# Mock imports for modules that won't be installed on RTD
autodoc_mock_imports = [
    'astrodata',
    'astropy',
    'gempy',
    'geminidr',
    'recipe_system',
    'photutils',
    'bokeh',
    'barycorrpy',
    'numpy',
    'numba',
    'pandas',
    'scipy',
    'lmfit',
    'astroquery',
    'matplotlib'
]

# Autodoc options - keep it simple to avoid hanging
autodoc_default_options = {
    'members': True,
    'undoc-members': False,
    'show-inheritance': False,
    # 'member-order': 'bysource',
    # 'exclude-members': '__init__, __weakref__, __dict__, __module__, __annotations__',
}

# Don't inherit docstrings to avoid deep introspection
autodoc_inherit_docstrings = False

# Timeout for autodoc imports (10 seconds)
autodoc_warningiserror = False

# Suppress specific warnings
suppress_warnings = ['app.add_directive']


# -- Intersphinx configuration --------------------------------------------

# Link to other Sphinx documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'astropy': ('https://docs.astropy.org/en/stable/', None),
}
