#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import pathlib
import sys

# -- Path setup ----------------------------------------------------------

# Add paths to sys.path so autoapi can find the modules
CURRENT_PATH = pathlib.Path(os.path.abspath(os.path.dirname(__file__)))
MX_PATH = CURRENT_PATH.parent.parent.parent  # Go up to MAROONXDR/

sys.path.insert(0, str(MX_PATH))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.imgmath',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.graphviz',
    'sphinx_rtd_theme',
    'sphinx_copybutton',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Maroon-X DRP: Programmer Manual'
copyright = '2025, MaroonX Team'
author = 'Martín Chalela García'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.4'
# The full version, including alpha/beta/rc tags.
release = '0.4.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
todo_link_only = True

# Auto-number figures, tables, and code blocks so :numref: references work in
# both HTML and PDF (e.g. Figure 3, Table 2). Also required for figures with
# :name: options to be reachable via :numref:.
numfig = True

# -- Autosummary configuration --------------------------------------------

# Don't generate separate stub pages - just create inline summaries
autosummary_generate = False
autosummary_imported_members = False

# -- Copybutton configuration ---------------------------------------------

# Configure copybutton to exclude prompts and comment lines
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
# Exclude lines starting with # (comments)
copybutton_exclude = '.highlight-bash .c1, .highlight-python .c1, .highlight .c1'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static', '../../_static']

# Custom CSS files
html_css_files = [
    'custom.css',
]

# Sidebar banner and browser-tab favicon (shared assets under doc/_static/)
html_logo = '../../_static/mx_banner.jpg'
html_favicon = '../../_static/mx_logo.png'

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     '**': [
#         'about.html',
#         'navigation.html',
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#         'donate.html',
#     ]
# }


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'maroonxprog'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # This will remove blank pages.
    'classoptions': ',openany,oneside',

    'babel': '\\usepackage[english]{babel}',

    # Load the custom.sty package copied in via latex_additional_files
    # below; it defines the colored envs used to style legacy-block /
    # dragons-block topics in the PDF build so they match the CSS
    # in the HTML build (custom.css mirrors this palette).
    #
    # Also load `placeins` with [section] so LaTeX auto-inserts a
    # \FloatBarrier before every \section, keeping figures under the
    # heading that introduces them instead of floating past it.
    'preamble': (
        r'\usepackage{custom}'
        '\n'
        r'\usepackage[section]{placeins}'
    ),

    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Copy the .sty package into the LaTeX build dir so \usepackage{} in the
# preamble above can find it. Kept next to custom.css so the CSS palette
# and its LaTeX mirror live side-by-side. A .sty extension (not .tex) is
# required so Sphinx's generated Makefile does not try to compile it as
# a standalone document.
latex_additional_files = ['_static/custom.sty']

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, f'MaroonXProgrammer-v{release}.tex', project,
     author, 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None
latex_logo = 'images/GeminiLogo_new_2014.jpg'

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'maroonxprog', project,
     [author], 1)
]


# -- Autoapi configuration removed ------------------------------------------------
# AutoAPI has been removed - using sphinx.ext.autodoc instead

# -- Autodoc configuration ------------------------------------------------

# Mock imports for DRAGONS modules that won't be installed on RTD
autodoc_mock_imports = [
    # 'astrodata',
    # 'astropy',
    # 'gempy',
    # 'geminidr',
    # 'recipe_system',
    # 'photutils',
    # 'bokeh',
    # 'barycorrpy',
    # 'numpy',
    # 'numba',
    # 'pandas',
    # 'scipy',
    # 'lmfit',
    # 'astroquery',
    # 'matplotlib'
]

# Autodoc options - include all members with or without docstrings
autodoc_default_options = {
    'members': True,
    'undoc-members': False,
    'show-inheritance': False,
    'member-order': 'bysource',
}

# Don't inherit docstrings to avoid deep introspection
autodoc_inherit_docstrings = False

# Suppress specific warnings
suppress_warnings = ['app.add_directive']

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'maroonxprog', project,
     author, 'maroonxprog',
     'Programmer manual for MaroonX data reduction software',
     'Miscellaneous'),
]


# -- Gemini style configuration -------------------------------------------

# Adding styles for:
#   - todos to show up in a red box
#   - setting table width and override rtd theme defaults
# def setup(app):
#     app.add_stylesheet('todo-styles.css')
#     app.add_stylesheet('rtd_theme_overrides.css')

# -- Intersphinx configuration --------------------------------------------

# Link to other Sphinx documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'astropy': ('https://docs.astropy.org/en/stable/', None),
    'astrodata': ('https://astrodata.readthedocs.io/en/latest/', None),
}
